/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedIndustryNameRouteImport } from './routes/_authenticated/industry.$name'
import { Route as AuthenticatedCountryNameRouteImport } from './routes/_authenticated/country.$name'
import { Route as AuthenticatedCompanyNameRouteImport } from './routes/_authenticated/company.$name'
import { Route as AuthenticatedCommodityNameRouteImport } from './routes/_authenticated/commodity.$name'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIndustryNameRoute =
  AuthenticatedIndustryNameRouteImport.update({
    id: '/industry/$name',
    path: '/industry/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCountryNameRoute =
  AuthenticatedCountryNameRouteImport.update({
    id: '/country/$name',
    path: '/country/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyNameRoute =
  AuthenticatedCompanyNameRouteImport.update({
    id: '/company/$name',
    path: '/company/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommodityNameRoute =
  AuthenticatedCommodityNameRouteImport.update({
    id: '/commodity/$name',
    path: '/commodity/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/commodity/$name': typeof AuthenticatedCommodityNameRoute
  '/company/$name': typeof AuthenticatedCompanyNameRoute
  '/country/$name': typeof AuthenticatedCountryNameRoute
  '/industry/$name': typeof AuthenticatedIndustryNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/commodity/$name': typeof AuthenticatedCommodityNameRoute
  '/company/$name': typeof AuthenticatedCompanyNameRoute
  '/country/$name': typeof AuthenticatedCountryNameRoute
  '/industry/$name': typeof AuthenticatedIndustryNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/commodity/$name': typeof AuthenticatedCommodityNameRoute
  '/_authenticated/company/$name': typeof AuthenticatedCompanyNameRoute
  '/_authenticated/country/$name': typeof AuthenticatedCountryNameRoute
  '/_authenticated/industry/$name': typeof AuthenticatedIndustryNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/history'
    | '/commodity/$name'
    | '/company/$name'
    | '/country/$name'
    | '/industry/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/history'
    | '/commodity/$name'
    | '/company/$name'
    | '/country/$name'
    | '/industry/$name'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/commodity/$name'
    | '/_authenticated/company/$name'
    | '/_authenticated/country/$name'
    | '/_authenticated/industry/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/industry/$name': {
      id: '/_authenticated/industry/$name'
      path: '/industry/$name'
      fullPath: '/industry/$name'
      preLoaderRoute: typeof AuthenticatedIndustryNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/country/$name': {
      id: '/_authenticated/country/$name'
      path: '/country/$name'
      fullPath: '/country/$name'
      preLoaderRoute: typeof AuthenticatedCountryNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/$name': {
      id: '/_authenticated/company/$name'
      path: '/company/$name'
      fullPath: '/company/$name'
      preLoaderRoute: typeof AuthenticatedCompanyNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commodity/$name': {
      id: '/_authenticated/commodity/$name'
      path: '/commodity/$name'
      fullPath: '/commodity/$name'
      preLoaderRoute: typeof AuthenticatedCommodityNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedCommodityNameRoute: typeof AuthenticatedCommodityNameRoute
  AuthenticatedCompanyNameRoute: typeof AuthenticatedCompanyNameRoute
  AuthenticatedCountryNameRoute: typeof AuthenticatedCountryNameRoute
  AuthenticatedIndustryNameRoute: typeof AuthenticatedIndustryNameRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedCommodityNameRoute: AuthenticatedCommodityNameRoute,
  AuthenticatedCompanyNameRoute: AuthenticatedCompanyNameRoute,
  AuthenticatedCountryNameRoute: AuthenticatedCountryNameRoute,
  AuthenticatedIndustryNameRoute: AuthenticatedIndustryNameRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
