/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedLanesRouteImport } from './routes/_authenticated/lanes'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDigestRouteImport } from './routes/_authenticated/digest'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBacktestRouteImport } from './routes/_authenticated/backtest'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as ApiPublicAlertDeliverRouteImport } from './routes/api/public/alert-deliver'
import { Route as AuthenticatedIndustryNameRouteImport } from './routes/_authenticated/industry.$name'
import { Route as AuthenticatedCountryNameRouteImport } from './routes/_authenticated/country.$name'
import { Route as AuthenticatedCompanyNameRouteImport } from './routes/_authenticated/company.$name'
import { Route as AuthenticatedCommodityNameRouteImport } from './routes/_authenticated/commodity.$name'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLanesRoute = AuthenticatedLanesRouteImport.update({
  id: '/lanes',
  path: '/lanes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDigestRoute = AuthenticatedDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBacktestRoute = AuthenticatedBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicAlertDeliverRoute = ApiPublicAlertDeliverRouteImport.update({
  id: '/api/public/alert-deliver',
  path: '/api/public/alert-deliver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndustryNameRoute =
  AuthenticatedIndustryNameRouteImport.update({
    id: '/industry/$name',
    path: '/industry/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCountryNameRoute =
  AuthenticatedCountryNameRouteImport.update({
    id: '/country/$name',
    path: '/country/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompanyNameRoute =
  AuthenticatedCompanyNameRouteImport.update({
    id: '/company/$name',
    path: '/company/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCommodityNameRoute =
  AuthenticatedCommodityNameRouteImport.update({
    id: '/commodity/$name',
    path: '/commodity/$name',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/backtest': typeof AuthenticatedBacktestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/digest': typeof AuthenticatedDigestRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/lanes': typeof AuthenticatedLanesRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/commodity/$name': typeof AuthenticatedCommodityNameRoute
  '/company/$name': typeof AuthenticatedCompanyNameRoute
  '/country/$name': typeof AuthenticatedCountryNameRoute
  '/industry/$name': typeof AuthenticatedIndustryNameRoute
  '/api/public/alert-deliver': typeof ApiPublicAlertDeliverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/backtest': typeof AuthenticatedBacktestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/digest': typeof AuthenticatedDigestRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/lanes': typeof AuthenticatedLanesRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/commodity/$name': typeof AuthenticatedCommodityNameRoute
  '/company/$name': typeof AuthenticatedCompanyNameRoute
  '/country/$name': typeof AuthenticatedCountryNameRoute
  '/industry/$name': typeof AuthenticatedIndustryNameRoute
  '/api/public/alert-deliver': typeof ApiPublicAlertDeliverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/backtest': typeof AuthenticatedBacktestRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/digest': typeof AuthenticatedDigestRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/lanes': typeof AuthenticatedLanesRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/commodity/$name': typeof AuthenticatedCommodityNameRoute
  '/_authenticated/company/$name': typeof AuthenticatedCompanyNameRoute
  '/_authenticated/country/$name': typeof AuthenticatedCountryNameRoute
  '/_authenticated/industry/$name': typeof AuthenticatedIndustryNameRoute
  '/api/public/alert-deliver': typeof ApiPublicAlertDeliverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/analytics'
    | '/backtest'
    | '/dashboard'
    | '/digest'
    | '/history'
    | '/lanes'
    | '/portfolio'
    | '/settings'
    | '/commodity/$name'
    | '/company/$name'
    | '/country/$name'
    | '/industry/$name'
    | '/api/public/alert-deliver'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/analytics'
    | '/backtest'
    | '/dashboard'
    | '/digest'
    | '/history'
    | '/lanes'
    | '/portfolio'
    | '/settings'
    | '/commodity/$name'
    | '/company/$name'
    | '/country/$name'
    | '/industry/$name'
    | '/api/public/alert-deliver'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/alerts'
    | '/_authenticated/analytics'
    | '/_authenticated/backtest'
    | '/_authenticated/dashboard'
    | '/_authenticated/digest'
    | '/_authenticated/history'
    | '/_authenticated/lanes'
    | '/_authenticated/portfolio'
    | '/_authenticated/settings'
    | '/_authenticated/commodity/$name'
    | '/_authenticated/company/$name'
    | '/_authenticated/country/$name'
    | '/_authenticated/industry/$name'
    | '/api/public/alert-deliver'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicAlertDeliverRoute: typeof ApiPublicAlertDeliverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lanes': {
      id: '/_authenticated/lanes'
      path: '/lanes'
      fullPath: '/lanes'
      preLoaderRoute: typeof AuthenticatedLanesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/digest': {
      id: '/_authenticated/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof AuthenticatedDigestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backtest': {
      id: '/_authenticated/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof AuthenticatedBacktestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/alert-deliver': {
      id: '/api/public/alert-deliver'
      path: '/api/public/alert-deliver'
      fullPath: '/api/public/alert-deliver'
      preLoaderRoute: typeof ApiPublicAlertDeliverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/industry/$name': {
      id: '/_authenticated/industry/$name'
      path: '/industry/$name'
      fullPath: '/industry/$name'
      preLoaderRoute: typeof AuthenticatedIndustryNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/country/$name': {
      id: '/_authenticated/country/$name'
      path: '/country/$name'
      fullPath: '/country/$name'
      preLoaderRoute: typeof AuthenticatedCountryNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/company/$name': {
      id: '/_authenticated/company/$name'
      path: '/company/$name'
      fullPath: '/company/$name'
      preLoaderRoute: typeof AuthenticatedCompanyNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commodity/$name': {
      id: '/_authenticated/commodity/$name'
      path: '/commodity/$name'
      fullPath: '/commodity/$name'
      preLoaderRoute: typeof AuthenticatedCommodityNameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBacktestRoute: typeof AuthenticatedBacktestRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDigestRoute: typeof AuthenticatedDigestRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedLanesRoute: typeof AuthenticatedLanesRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCommodityNameRoute: typeof AuthenticatedCommodityNameRoute
  AuthenticatedCompanyNameRoute: typeof AuthenticatedCompanyNameRoute
  AuthenticatedCountryNameRoute: typeof AuthenticatedCountryNameRoute
  AuthenticatedIndustryNameRoute: typeof AuthenticatedIndustryNameRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBacktestRoute: AuthenticatedBacktestRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDigestRoute: AuthenticatedDigestRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedLanesRoute: AuthenticatedLanesRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCommodityNameRoute: AuthenticatedCommodityNameRoute,
  AuthenticatedCompanyNameRoute: AuthenticatedCompanyNameRoute,
  AuthenticatedCountryNameRoute: AuthenticatedCountryNameRoute,
  AuthenticatedIndustryNameRoute: AuthenticatedIndustryNameRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicAlertDeliverRoute: ApiPublicAlertDeliverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
